import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { io } from "socket.io-client"
import { useEffect, useState } from 'react'

const socket = io('http://localhost:8000')

export default function Home() {
  const [chatText, setChatText] = useState("") // chat Typed in input
  const [chatPrint, setChatPrint] = useState([]) // chat received from server


  // use for reference of id
  const [newUserInputBox, setNewUserInputBox] = useState("") // what user typed in nickname input box

/* Need to figure out how to have multiple nickname users */

  // This is what we receive back from server
  const [nickname, setNickName] = useState('')



  // sends 'chatText' to server
  const sendChat = () => { // 
    socket.emit("chatToServer", chatText)
  }
  // server listener for 'chatToClient' 
  socket.on('chatToClient', (data) => {
    if (data !== null && data.trim() !== "") setChatPrint([...chatPrint, data])
    setChatText("")
  })


  socket.on('nicknameToClient', (data) => {
    setNickName(data)

  })

  const sendUserToServer = (e) => {
    socket.emit("newUser", newUserInputBox)
  }
  return (
    <>
      <Head>
        <title>Chat app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>

        <div className={styles.pageContainer}>


          <div className={styles.chatContainer}>

            <div className={styles.chatSentContainer}>
              {chatPrint.map((e) => (
                <div className={styles.chatStyle}>
{/*                   {nickname == nicknameSaved ?
                    ( 
    */}
                      <>
                        <div className={styles.chatSender}>{nickname}:</div>
                        <div>{e}</div>
                      </>
{/*                     )
                    : 
                    (
                      <>
                        <div className={styles.chatReceiver}>{nickname}:</div>
                        <div>{e}</div>
                      </>
                    )}  
*/}

                </div>
              ))}
            </div>

            <div className={styles.bottomContainer}>
              <input type="text" value={chatText} className={styles.inputBox} onChange={(e) => setChatText(e.target.value)}></input>
              <button className={styles.sendButton} onClick={sendChat}>Send</button>
            </div>
          </div>
        </div>
        <div className={styles.nicknameContainer}>
          Nickname:
          <input type="text" value={newUserInputBox} className={styles.nicknameInput} onChange={(e) => setNewUserInputBox(e.target.value)}></input>
          <button className={styles.nicknameButton} onClick={sendUserToServer}>Send</button>

        </div>
      </main>
    </>
  )
}