import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { io } from "socket.io-client"
import { useEffect, useState } from 'react'

const socket = io('http://localhost:8000')

export default function Home() {
  const [userBox, setUserBox] = useState('') // chat typed in userBox
  const [chatBox, setChatBox] = useState('') // chat Typed in input

  // object used to setMessage
  /*   const messageFormat = {
      user: '',
      chatMessage: ''
    } */
  const [message, setMessage] = useState({})

  const [messageFromServer, setMessageFromServer] = useState([]) // chat received from server

  const sendMessageToServer = () => {
    socket.emit("messageToServer", message)
    console.log(message)
  }


  socket.on('messageToClient', (data) => {
    /*  if (data['chatMessage'] !== null && data['chatMessage'].trim() !== "")  */
    setMessageFromServer([...messageFromServer, data])
    // setChatBox('')
  })

  return (
    <>
      <Head>
        <title>Chat app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={styles.main}>
        <div className={styles.pageContainer}>

          <form onSubmit={(e) => {
            e.preventDefault()
            setMessage({ user: userBox })
          }} className={styles.nicknameContainer}>
            Nickname:
            <input type="text" className={styles.nicknameInput} onChange={(e) => setUserBox(e.target.value)}></input>
            <button className={styles.nicknameButton} value="Submit" type="submit">Send</button>
          </form>

          <div className={styles.chatContainer}>
            <div className={styles.chatSentContainer}>


              {messageFromServer.map((e, i) => (
                <div key={i} className={styles.chatStyle}>
                  <div className={styles.chatSender}>{e.user}:</div>
                  <div>{e.chatMessage}</div>
                </div>
              ))}  
 

            </div>

            <form onSubmit={(e) => {
              e.preventDefault()
              sendMessageToServer()
            }} className={styles.bottomContainer}>

              <input type="text" className={styles.inputBox} onChange={(e) => setMessage({ user: userBox, chatMessage: e.target.value })}></input>
              <button className={styles.sendButton} value="Submit" type="submit">Send</button>

            </form>
          </div>
        </div>

      </main>
    </>
  )
}